"""Data models for VMFree VM definitions.

These dataclasses represent the parsed state of a VMware virtual machine,
independent of the source format (VMX, OVF, raw VMDK). Every stage of
the migration pipeline operates on these structures.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path


class Firmware(Enum):
    """VM firmware type."""

    BIOS = "bios"
    EFI = "efi"


class DiskType(Enum):
    """VMDK disk storage type."""

    MONOLITHIC_SPARSE = "monolithicSparse"
    MONOLITHIC_FLAT = "monolithicFlat"
    TWO_GB_MAX_EXTENT_SPARSE = "twoGbMaxExtentSparse"
    TWO_GB_MAX_EXTENT_FLAT = "twoGbMaxExtentFlat"
    VMFS = "vmfs"
    VMFS_SPARSE = "vmfsSparse"
    VMFS_THIN = "vmfsThin"
    SE_SPARSE = "seSparse"
    STREAM_OPTIMIZED = "streamOptimized"
    UNKNOWN = "unknown"


@dataclass
class DiskDefinition:
    """A single virtual disk attached to a VM.

    Attributes:
        path: Path to the VMDK descriptor file (not the -flat.vmdk).
        controller: Controller bus the disk is on (e.g. "scsi0", "ide0", "sata0").
        unit: Unit/slot number on the controller.
        size_bytes: Virtual disk size in bytes (0 if unknown until VMDK is inspected).
        disk_type: VMDK storage type (sparse, flat, etc.).
        is_boot: Whether this is the boot disk (first disk on first controller).
    """

    path: str
    controller: str = "scsi0"
    unit: int = 0
    size_bytes: int = 0
    disk_type: DiskType = DiskType.UNKNOWN
    is_boot: bool = False


@dataclass
class NICDefinition:
    """A single network interface attached to a VM.

    Attributes:
        virtual_dev: VMware virtual NIC type (vmxnet3, e1000, e1000e, vlance).
        mac_address: MAC address (may be empty if auto-generated by VMware).
        connection_type: VMware connection type (bridged, nat, hostonly, custom).
        network_name: VMware virtual network name (e.g. "VM Network"), if set.
    """

    virtual_dev: str = "e1000"
    mac_address: str = ""
    connection_type: str = "bridged"
    network_name: str = ""


@dataclass
class VMDefinition:
    """Complete definition of a virtual machine parsed from VMware config.

    This is the central data structure that flows through the entire
    migration pipeline: parsers produce it, mappers transform it,
    generators consume it.

    Attributes:
        name: Display name of the VM.
        guest_os: VMware guest OS identifier (e.g. "ubuntu-64", "windows9-64").
        memory_mb: RAM in megabytes.
        vcpus: Number of virtual CPUs.
        firmware: Boot firmware (BIOS or EFI).
        disks: List of attached virtual disks.
        nics: List of attached network interfaces.
        scsi_controller: Primary SCSI controller type (pvscsi, lsilogic, buslogic, etc.).
        display: VMware display adapter type (svga, vmware).
        source_file: Path to the original VMware config file that was parsed.
        hardware_version: VMware virtual hardware version number.
    """

    name: str
    guest_os: str = ""
    memory_mb: int = 1024
    vcpus: int = 1
    firmware: Firmware = Firmware.BIOS
    disks: list[DiskDefinition] = field(default_factory=list)
    nics: list[NICDefinition] = field(default_factory=list)
    scsi_controller: str = ""
    display: str = "svga"
    source_file: Path | None = None
    hardware_version: int = 0

    @property
    def is_windows(self) -> bool:
        """Detect if this is a Windows guest based on the guestOS identifier."""
        windows_hints = ("windows", "win31", "win95", "win98", "winnt", "winme",
                         "winxp", "win2000", "longhorn", "vista")
        os_lower = self.guest_os.lower()
        return any(hint in os_lower for hint in windows_hints)

    @property
    def is_efi(self) -> bool:
        """Check if this VM uses EFI firmware."""
        return self.firmware == Firmware.EFI

    @property
    def boot_disk(self) -> DiskDefinition | None:
        """Return the boot disk, or the first disk if none is marked as boot."""
        for disk in self.disks:
            if disk.is_boot:
                return disk
        return self.disks[0] if self.disks else None
